## Settings
markdown: kramdown
theme: jekyll-theme-hacker

## Global Variables
title: Jady Ray, Chang'an University
description: "行百里者半九十<br>
　∧＿∧<br>
（｡･ω･｡)つ━☆.. ・*。<br>
⊂　　 ノ 　 　　・゜+.<br>
　しーＪ　 　　°。+ *´¨)<br>
　　　 　　.· ´¸.·*´¨) ¸.·*¨)<br>
　　　　　　 　 　(¸.·´ (¸.·’*"
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√§"

# path
assets_path: "/assets"

permalink: /blog/:year/:month/:day/:title
